version: '3.1'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        build: nginx-balance
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
            - ./certificates:/etc/nginx/certificates

        wordpress:
            image: wordpress
            container_name: wordpress_1
            links: 
                - mariadb: mysql
            expose: 
                - 80
            environment: 
                - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
                - WORDPRESS_DB_USER=${DB_USER}
                - WORDPRESS_DB_NAME=${DB_NAME}
                - VIRTUAL_HOST=${HOST}
            volumes: 
                - ./html:/var/www/html
            
        wordpress2:
            image: wordpress
            container_name: wordpress_2
            links: 
                - mariadb: mysql
            expose: 
                - 80
            environment: 
                - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
                - WORDPRESS_DB_USER=${DB_USER}
                - WORDPRESS_DB_NAME=${DB_NAME}
                - VIRTUAL_HOST=${HOST}
            volumes: 
                - ./html:/var/www/html
        
        mariadb:
            image: mariadb
            environment: 
                - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
                - MYSQL_DATABASE=${DATABASE}
                - MYSQL_USER=${USER}
                - MYSQL_PASSWORD=${PASSWORD}
            volumes: 
                - ./data:/var/lib/mysql
        redis:
            image: redis
            container_name: redis_cache
            ports: 
                - "6379:6379"
            volumes: 
                - ./redis_cache:/data
        