version: "3.2"

services:
    db:
        image: mysql:5.7
        env_file: 
            - .env
        volumes:
          - ./db_data:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=$ROOT_PASSWORD
          - MYSQL_DATABASE=$MY_DATABASE
          - MYSQL_USER=$MY_USER
          - MYSQL_PASSWORD=$MY_PASSWORD

    wordpress1:
        depends_on:
            - db
        image: wordpress:latest
        container_name: wp1
        env_file: 
            - .env
        expose:
            - 80
        environment:
            - WORDPRESS_DB_HOST=$DB_HOST
            - WORDPRESS_DB_USER=$DB_USER
            - WORDPRESS_DB_PASSWORD=$DB_PASSWORD
            - VIRTUAL_HOST=lesliejoan.com,www.lesliejoan.com
            - LETSENCRYPT_HOST=lesliejoan.com,www.lesliejoan.com
            - LETSENCRYPT_EMAIL=franelreal@gmail.com
        volumes: 
            - ./html:/var/www/html

    wordpress2:
        depends_on:
            - db
        image: wordpress:latest
        container_name: wp2
        env_file: 
            - .env
        expose:
            - 80
        environment:
            - WORDPRESS_DB_HOST=$DB_HOST
            - WORDPRESS_DB_USER=$DB_USER
            - WORDPRESS_DB_PASSWORD=$DB_PASSWORD
            - VIRTUAL_HOST=lesliejoan.com,www.lesliejoan.com
            - LETSENCRYPT_HOST=lesliejoan.com,www.lesliejoan.com
            - LETSENCRYPT_EMAIL=franelreal@gmail.com
        volumes: 
            - ./html:/var/www/html            

    proxy:
        image: jwilder/nginx-proxy
        container_name: proxy
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - certs:/etc/nginx/certs
            - vhostd:/etc/nginx/vhost.d
            - ./html:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt
        environment: 
            - NGINX_PROXY_CONTAINER=proxy
        volumes:
            - certs:/etc/nginx/certs
            - vhostd:/etc/nginx/vhost.d
            - ./html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro
    redis:
      image: redis
      container_name: redis_caches
      ports:
         - "6379:6379"
 
volumes:
    certs:
    vhostd:
